### PR TITLE
use my basic_materials mod where possible

### PR DESCRIPTION
**Pull request by VanessaE**

### CODE REVIEW

**Comment by SmallJoker** [comment]
How about aliases? Not needed?

**Comment by VanessaE** [comment]
Shouldn't be -- I tried to make sure `basic_materials` already had aliases for all of the mods that it seeks to supplement.

**Comment by SmallJoker** [comment]
Looks about right. `glooptest_chainlink.png` should be removed too (unused).

**Comment by VanessaE** [comment]
fixed, "by force" :smile:

**Pull request merged**
